name: Unit & Integration Tests

on:
  push:
    branches: [ "master" ]
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/tests.yml"
      - "pyproject.toml"
  pull_request:
    branches: [ "master" ]
    paths:
      - "src/**"
      - "tests/**"
      - ".github/workflows/tests.yml"
      - "pyproject.toml"

env:
  PYTHONPATH: "src"  # for tests to import src/airflow_clickhouse_plugin

jobs:

  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        airflow-version: ["2.3.4", "2.4.3", "2.5.3", "2.6.3", "2.7.3", "2.8.4", "2.9.3", "2.10.5", "2.11.2", "3.0.6", "3.1.8", "3.2.1"]
        extras: ["", "[common.sql,openlineage]"]
        include:
          # if no extras installed => run only clickhouse-driver native tests
          - extras: ""
            tests-pattern: "-p test_clickhouse.py"
          # if all extras installed => run all tests
          - extras: "[common.sql,openlineage]"
            tests-pattern: ""
        exclude:
          # constraints files for these combinations are missing
          - python-version: "3.11"
            airflow-version: "2.3.4"
          - python-version: "3.11"
            airflow-version: "2.4.3"
          - python-version: "3.11"
            airflow-version: "2.5.3"
          - python-version: "3.12"
            airflow-version: "2.3.4"
          - python-version: "3.12"
            airflow-version: "2.4.3"
          - python-version: "3.12"
            airflow-version: "2.5.3"
          - python-version: "3.12"
            airflow-version: "2.6.3"
          - python-version: "3.12"
            airflow-version: "2.7.3"
          - python-version: "3.12"
            airflow-version: "2.8.4"
          - python-version: "3.13"
            airflow-version: "2.3.4"
          - python-version: "3.13"
            airflow-version: "2.4.3"
          - python-version: "3.13"
            airflow-version: "2.5.3"
          - python-version: "3.13"
            airflow-version: "2.6.3"
          - python-version: "3.13"
            airflow-version: "2.7.3"
          - python-version: "3.13"
            airflow-version: "2.8.4"
          - python-version: "3.13"
            airflow-version: "2.9.3"
          - python-version: "3.13"
            airflow-version: "2.10.5"
          - python-version: "3.13"
            airflow-version: "2.11.2"
          - python-version: "3.13"
            airflow-version: "3.0.6"
          - python-version: "3.14"
            airflow-version: "2.3.4"
          - python-version: "3.14"
            airflow-version: "2.4.3"
          - python-version: "3.14"
            airflow-version: "2.5.3"
          - python-version: "3.14"
            airflow-version: "2.6.3"
          - python-version: "3.14"
            airflow-version: "2.7.3"
          - python-version: "3.14"
            airflow-version: "2.8.4"
          - python-version: "3.14"
            airflow-version: "2.9.3"
          - python-version: "3.14"
            airflow-version: "2.10.5"
          - python-version: "3.14"
            airflow-version: "2.11.2"
          - python-version: "3.14"
            airflow-version: "3.0.6"
          - python-version: "3.14"
            airflow-version: "3.1.8"
          # common.sql constraint for these Airflow versions is <1.3.0
          #   => misses SQLExecuteQueryOperator
          #   => pip install will fail on this combination
          - extras: "[common.sql,openlineage]"
            airflow-version: "2.0.3"
          - extras: "[common.sql,openlineage]"
            airflow-version: "2.1.4"
          - extras: "[common.sql,openlineage]"
            airflow-version: "2.2.5"
          - extras: "[common.sql,openlineage]"
            airflow-version: "2.3.4"
          - extras: "[common.sql,openlineage]"
            airflow-version: "2.4.3"
          # common.sql constraint for these Airflow versions is <1.6.0
          #   while openlineage requires common.sql>=1.6.0
          #   => pip install will fail on this combination
          - extras: "[common.sql,openlineage]"
            airflow-version: "2.5.3"
          - extras: "[common.sql,openlineage]"
            airflow-version: "2.6.3"
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv
      uses: astral-sh/setup-uv@v8.1.0
    - name: Install dependencies
      run: |
        uv pip install --system -e .${{ matrix.extras }} \
          apache-airflow==${{ matrix.airflow-version }} \
          --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-${{ matrix.airflow-version }}/constraints-${{ matrix.python-version }}.txt"
    - name: Run unit tests
      run: |
        uv run -m unittest discover -t tests -s unit ${{ matrix.tests-pattern }}

  integration-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        airflow-version: ["2.3.4", "2.4.3", "2.5.3", "2.6.3", "2.7.3", "2.8.4", "2.9.3", "2.10.5", "2.11.2", "3.0.6", "3.1.8", "3.2.1"]
        extras: ["", "[common.sql,openlineage]"]
        include:
          # if no extras installed => run only clickhouse-driver native tests
          - extras: ""
            tests-pattern: "-p test_clickhouse.py"
          # if all extras installed => run all tests
          - extras: "[common.sql,openlineage]"
            tests-pattern: ""
        exclude:
          # constraints files for these combinations are missing
          - python-version: "3.11"
            airflow-version: "2.3.4"
          - python-version: "3.11"
            airflow-version: "2.4.3"
          - python-version: "3.11"
            airflow-version: "2.5.3"
          - python-version: "3.12"
            airflow-version: "2.3.4"
          - python-version: "3.12"
            airflow-version: "2.4.3"
          - python-version: "3.12"
            airflow-version: "2.5.3"
          - python-version: "3.12"
            airflow-version: "2.6.3"
          - python-version: "3.12"
            airflow-version: "2.7.3"
          - python-version: "3.12"
            airflow-version: "2.8.4"
          - python-version: "3.13"
            airflow-version: "2.3.4"
          - python-version: "3.13"
            airflow-version: "2.4.3"
          - python-version: "3.13"
            airflow-version: "2.5.3"
          - python-version: "3.13"
            airflow-version: "2.6.3"
          - python-version: "3.13"
            airflow-version: "2.7.3"
          - python-version: "3.13"
            airflow-version: "2.8.4"
          - python-version: "3.13"
            airflow-version: "2.9.3"
          - python-version: "3.13"
            airflow-version: "2.10.5"
          - python-version: "3.13"
            airflow-version: "2.11.2"
          - python-version: "3.13"
            airflow-version: "3.0.6"
          - python-version: "3.14"
            airflow-version: "2.3.4"
          - python-version: "3.14"
            airflow-version: "2.4.3"
          - python-version: "3.14"
            airflow-version: "2.5.3"
          - python-version: "3.14"
            airflow-version: "2.6.3"
          - python-version: "3.14"
            airflow-version: "2.7.3"
          - python-version: "3.14"
            airflow-version: "2.8.4"
          - python-version: "3.14"
            airflow-version: "2.9.3"
          - python-version: "3.14"
            airflow-version: "2.10.5"
          - python-version: "3.14"
            airflow-version: "2.11.2"
          - python-version: "3.14"
            airflow-version: "3.0.6"
          - python-version: "3.14"
            airflow-version: "3.1.8"
          # common.sql constraint for these Airflow versions is <1.3.0
          #   => misses SQLExecuteQueryOperator
          #   => pip install will fail on this combination
          - extras: "[common.sql,openlineage]"
            airflow-version: "2.0.3"
          - extras: "[common.sql,openlineage]"
            airflow-version: "2.1.4"
          - extras: "[common.sql,openlineage]"
            airflow-version: "2.2.5"
          - extras: "[common.sql,openlineage]"
            airflow-version: "2.3.4"
          - extras: "[common.sql,openlineage]"
            airflow-version: "2.4.3"
          # common.sql constraint for these Airflow versions is <1.6.0
          #   while openlineage requires common.sql>=1.6.0
          #   => pip install will fail on this combination
          - extras: "[common.sql,openlineage]"
            airflow-version: "2.5.3"
          - extras: "[common.sql,openlineage]"
            airflow-version: "2.6.3"
    services:
      clickhouse:
        image: clickhouse/clickhouse-server
        ports:
          - 9000/tcp
        options: >-
          --env CLICKHOUSE_SKIP_USER_SETUP=1
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install uv
      uses: astral-sh/setup-uv@v8.1.0
    - name: Install dependencies
      run: |
        uv pip install --system -e .${{ matrix.extras }} \
          apache-airflow==${{ matrix.airflow-version }} \
          --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-${{ matrix.airflow-version }}/constraints-${{ matrix.python-version }}.txt"
    - name: Run tests on ClickHouse server
      env:
        AIRFLOW_CONN_CLICKHOUSE_DEFAULT: "clickhouse://localhost:${{ job.services.clickhouse.ports['9000'] }}"
      run: |
        uv run -m unittest discover -t tests -s integration ${{ matrix.tests-pattern }}
